---
apt_packages:
  - make
  - g++
  - libpq-dev
  - mc
  - vim
  - ruby2.5-dev

ruby_version: 2.5

postgresql_databases:
  - name: player_statistics
    owner: user_player_statistics

postgresql_users:
  - name: user_player_statistics
    pass: 123456

postgresql_user_privileges:
  - name: user_player_statistics
    db: player_statistics
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
